import { defineConfig } from 'cspell';

export default defineConfig({
  ignorePaths: ['node_modules', 'dist', 'coverage', 'playwright-report', 'test-results', '.lighthouseci'],
  words: [
    'autorun',
    'Catppuccin',
    'contentinfo',
    'daisyui',
    'Fira',
    'fontsource',
    'GHSA',
    'inspectable',
    'lhci',
    'lighthouseci',
    'lighthouserc',
    'lockfiles',
    'Macchiato',
    'Mohandas',
    'prefersdark',
    'preminor',
    'rahul',
    'rahulmohandas',
    'SLSA',
    'subpaths',
    'Sveltia',
    'unreviewed',
    'viewports',
    'WCAG',
    'Zizmor',
  ],
});
