name: Repository Automation Validation
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "43 5 * * 1"
permissions: {}
concurrency:
  group: "${{ github.workflow_ref }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: "false"
      - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          advanced-security: "true"
          collect: all
  syntax:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: "false"
      - uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2
